name: Release Binary

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. 1.0.0 - without v)'
        required: true
        default: '1.0.0'

  push:
    tags:
      - 'v*' 

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build Release Binary
      run: cargo build --release

    - name: Rename Binary
      run: cp target/release/clean-my-keys ./clean-my-keys-linux-amd64

    - name: Set Release Tag
      id: vars
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "tag=v${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          # Extract the tag from the Git ref (e.g. refs/tags/v1.0.0 -> v1.0.0)
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.vars.outputs.tag }}
        name: Release ${{ steps.vars.outputs.tag }}
        files: clean-my-keys-linux-amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}